#!/usr/bin/env node
/*
 * Builds the CV Playground into ./_site.
 *
 * Reads every templates/<name>/demo.html, embeds them into templates.js as
 * a JS object (so the page needs no runtime fetch and works on any static
 * host), and copies index.html alongside it. Run from the repo root or from
 * playground/ — paths are resolved relative to this file.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const tplDir = path.join(root, "templates");
const outDir = path.resolve(process.argv[2] || path.join(root, "_site"));

// Preferred display order; any extra templates are appended alphabetically.
const PREFERRED = ["meridian", "datum", "keystone", "prism", "quill"];

function readTemplates() {
  const names = fs
    .readdirSync(tplDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((n) => fs.existsSync(path.join(tplDir, n, "demo.html")));

  const order = [
    ...PREFERRED.filter((n) => names.includes(n)),
    ...names.filter((n) => !PREFERRED.includes(n)).sort(),
  ];

  const templates = {};
  for (const n of order) {
    templates[n] = fs.readFileSync(path.join(tplDir, n, "demo.html"), "utf8");
  }
  return { order, templates };
}

function main() {
  const { order, templates } = readTemplates();
  if (!order.length) {
    console.error("No templates found in " + tplDir);
    process.exit(1);
  }

  fs.mkdirSync(outDir, { recursive: true });

  const js =
    "// Generated by playground/build.js — do not edit by hand.\n" +
    "window.CV_TEMPLATE_ORDER = " + JSON.stringify(order) + ";\n" +
    "window.CV_TEMPLATES = " + JSON.stringify(templates) + ";\n";
  fs.writeFileSync(path.join(outDir, "templates.js"), js);

  fs.copyFileSync(
    path.join(__dirname, "index.html"),
    path.join(outDir, "index.html")
  );

  // Prevent Jekyll from touching the static output on GitHub Pages.
  fs.writeFileSync(path.join(outDir, ".nojekyll"), "");

  console.log(
    "Built playground → " + path.relative(process.cwd(), outDir) +
    " (" + order.length + " templates: " + order.join(", ") + ")"
  );
}

main();
